CodeSystem: PlacementQualifierCS
Id: placement-qualifier-cs
Title: "Placement Qualifier Code System"
Description: "Placement qualifiers that state whether the preferred or the affected body structure is meant."
* ^experimental = false
* #preferred "Preferred"
* #affected "Affected"

CodeSystem: AttachmentMethodCS
Id: attachment-method-cs
Title: "Attachment Method Code System"
Description: "How a wearable IMU sensor, or the device housing it, is fixed to the body or to clothing."
* ^experimental = false
* #pocket "Pocket" "Device carried loose inside a garment pocket, not otherwise fixed to the body."
* #belt "Belt" "Device threaded onto, or clipped to, a waist belt."
* #pouch "Pouch" "Device carried in a dedicated pouch worn on the body, distinct from a garment pocket."
* #clip "Clip" "Device fastened directly to clothing with a clip mechanism, without a pocket, pouch, or belt."
* #frame-mounted "Frame-mounted" "Device mounted on the frame of eyewear."
* #footwear-mounted "Footwear-mounted" "Device built into or fixed to footwear."
* #armband "Armband" "Device secured to the upper arm with an armband."
* #watch-strap "Watch strap" "Device worn on the wrist via a watch-style strap (e.g. a smartwatch or wrist-mounted sensor), distinct from the general-purpose Strap concept reused from SNOMED CT."
* #adhesive "Adhesive" "Device fixed directly to the skin with a medical-grade adhesive film or patch, without any strap, clip, or garment involved."
* #garment-integrated "Garment-integrated" "Sensor built into, sewn into, or otherwise integrated with a garment, so that the garment itself carries the sensor rather than holding a separate, removable device."
* #unconstrained-carry "Unconstrained carry" "Device carried by the participant without a prescribed attachment or position, for example a smartphone kept wherever the participant chose during the recording. Recorded explicitly so that a deliberately unconstrained protocol is distinguishable from an attachment method that is simply unknown or unreported."
* #elastic-strap "Elastic strap" "Device worn on the body via an elastic strap, distinct from the general-purpose Strap concept reused from SNOMED CT."

CodeSystem: HARActivityLabelsCS
Id: har-activity-labels-cs
Title: "HAR Activity Labels Code System"
Description: "General human activity recognition (HAR) labels for locomotion, posture, stair and elevator use, cycling and gym exercises. The concepts come from the HAR datasets reviewed in the paper (Table 1, full lists in Supplementary Table S1), for which no suitable LOINC or SNOMED CT code was found. Activities that appear under different names in different datasets (e.g. biking and cycling) are merged into one concept. Datasets with large action sets (REALDISP, UTD-MHAD and the atomic activities of CogAge) are only covered at the level of generic concepts such as jumping or arm raising."
* ^experimental = false
* #walking "Walking" "Ambulation at a normal, unspecified pace on a level indoor or outdoor surface."
* #walking-carrying-object "Walking while carrying an object" "Ambulation while carrying an object in one or both hands."
* #walking-forward "Walking forward" "Straight-line ambulation in the direction the participant is facing."
* #walking-leftward "Walking left-circling" "Ambulation along a leftward-curving or circling path."
* #walking-rightward "Walking right-circling" "Ambulation along a rightward-curving or circling path."
* #treadmill-walking "Treadmill walking, level" "Walking on a motorised treadmill at a fixed speed with no incline."
* #treadmill-walking-incline "Treadmill walking, inclined" "Walking on a motorised treadmill with the deck inclined."
* #jogging "Jogging" "Ambulation at a pace between walking and running."
* #running "Running" "Ambulation at a running pace on a level indoor or outdoor surface."
* #treadmill-running "Treadmill running" "Running on a motorised treadmill at a fixed speed."
* #nordic-walking "Nordic walking" "Walking with the aid of poles, engaging the upper body."
* #sitting "Sitting" "Seated, at rest."
* #standing "Standing" "Upright, stationary, at rest."
* #standing-talking "Standing, talking" "Standing while engaged in conversation, in person."
* #standing-talking-on-phone "Standing, talking on the phone" "Standing while engaged in a phone call."
* #sitting-talking-on-phone "Sitting, talking on the phone" "Sitting while engaged in a phone call."
* #lying "Lying" "Recumbent, at rest, side/position not further specified."
* #lying-reading-or-using-computer "Lying while reading or using a computer" "Recumbent while reading or operating a computer."
* #lying-supine "Lying on the back" "Recumbent, supine (on the back)."
* #lying-right-side "Lying on the right side" "Recumbent, on the right side."
* #sleeping "Sleeping" "Asleep, at rest."
* #kneeling-other "Kneeling, other activity" "Kneeling while performing an unspecified household task."
* #kneeling-making-barbecue-fire "Kneeling, lighting a barbecue" "Kneeling while lighting a barbecue fire."
* #stair-ascent "Ascending stairs" "Walking up a flight of stairs."
* #stair-descent "Descending stairs" "Walking down a flight of stairs."
* #stairs-unspecified-direction "Using stairs, direction unspecified" "Ascending or descending stairs; the source dataset does not distinguish direction."
* #elevator-ascent "Riding an elevator upward" "Riding an elevator travelling upward, including the walking/waiting segments of the transition."
* #elevator-descent "Riding an elevator downward" "Riding an elevator travelling downward, including the walking/waiting segments of the transition."
* #standing-in-stationary-elevator "Standing in a stationary elevator" "Standing still inside an elevator car that is not moving."
* #standing-in-moving-elevator "Standing in a moving elevator" "Standing still inside an elevator car while it is in motion."
* #cycling "Cycling" "Riding a bicycle, outdoors or on a road."
* #stationary-cycling-horizontal "Stationary cycling, horizontal bike" "Pedalling on a stationary exercise bike in the standard horizontal riding position."
* #stationary-cycling-vertical "Stationary cycling, recumbent/vertical bike" "Pedalling on a stationary exercise bike in the upright/recumbent vertical configuration."
* #rowing "Rowing" "Rowing motion, on a rowing machine or ergometer."
* #jumping "Jumping" "Jumping in place or short repeated jumps."
* #rope-jumping "Rope jumping" "Jumping rope."
* #stepper-exercise "Stepper exercise" "Exercising on a stair-stepper machine."
* #cross-trainer-exercise "Cross-trainer exercise" "Exercising on an elliptical cross-trainer machine."
* #trunk-twisting "Trunk twisting" "Rotational twisting movement of the trunk."
* #waist-bending "Waist bending" "Forward or lateral bending at the waist."
* #arm-raising "Arm raising / lifting" "Raising or lifting the arm(s), repeated or held."
* #knee-crouching "Knee bending / crouching" "Bending the knees into a crouched position."
* #playing-basketball "Playing basketball" "Playing basketball."
* #playing-soccer "Playing soccer" "Playing soccer/football."
* #bench-dips "Bench dips" "Triceps dip exercise performed using a bench."
* #squats "Squats" "Squatting exercise."
* #side-raises "Side raises" "Lateral arm-raise exercise."
* #shoulder-press "Shoulder press" "Overhead pressing exercise for the shoulders."
* #bicep-curl "Bicep curl" "Elbow-flexion curl exercise."
* #triceps-extension "Triceps extension" "Elbow-extension exercise targeting the triceps."
* #chest-press "Chest press" "Horizontal pressing exercise for the chest."
* #push-ups "Push-ups" "Push-up exercise."
* #chest-fly "Chest fly" "Chest-fly exercise."
* #bent-over-row "Bent-over row" "Bent-over rowing exercise for the back."

CodeSystem: GeriatricAssessmentLabelsCS
Id: geriatric-assessment-labels-cs
Title: "Geriatric Assessment Labels Code System"
Description: "Labels for structured clinical assessments, rehabilitation exercises, falls and postural transitions in the automatic geriatric assessment use case: Otago Exercise Programme movements (Shang 2024), shoulder rehabilitation exercises (Lee 2024), freezing of gait (Daphnet), simulated falls (MobiAct, UniMiB SHAR) and postural transitions (HAPT/SBHAR, UniMiB SHAR, MobiAct). Only labels that result from a prescribed test or exercise are included here; everyday household activities are in ADLLabelsCS. The LOINC codes for the TUG and 30-second chair stand test and the walking code from HARActivityLabelsCS are included directly in the GeriatricAssessmentLabels value set and are not repeated here."
* ^experimental = false
* #rest-position "Rest / no movement" "Baseline resting condition with no active movement, used as a reference class rather than a rehabilitation exercise."
* #sit-to-stand-transition "Sit-to-stand transition" "Rising from a seated to a standing position."
* #sit-to-lie-transition "Sit-to-lie transition" "Moving from a seated to a recumbent position."
* #stand-to-sit-transition "Stand-to-sit transition" "Sitting down from a standing position, e.g. onto a chair."
* #lie-to-sit-transition "Lie-to-sit transition" "Moving from a recumbent to a seated position."
* #stand-to-lie-transition "Stand-to-lie transition" "Lying down from a standing position."
* #lie-to-stand-transition "Lie-to-stand transition" "Standing up from a recumbent position."
* #shoulder-forward-flexion "Shoulder forward flexion" "Rehabilitation exercise: raising the arm forward at the shoulder."
* #shoulder-abduction "Shoulder abduction" "Rehabilitation exercise: raising the arm laterally away from the body."
* #shoulder-external-rotation "Shoulder external rotation" "Rehabilitation exercise: rotating the arm outward at the shoulder."
* #shoulder-internal-rotation "Shoulder internal rotation" "Rehabilitation exercise: rotating the arm inward at the shoulder."
* #shoulder-scaption "Shoulder scaption" "Rehabilitation exercise: raising the arm in the scapular plane, between flexion and abduction."
* #shoulder-horizontal-abduction "Shoulder horizontal abduction" "Rehabilitation exercise: moving the arm backward across the horizontal plane."
* #shoulder-horizontal-adduction "Shoulder horizontal adduction" "Rehabilitation exercise: moving the arm across the body in the horizontal plane."
* #shoulder-extension "Shoulder extension" "Rehabilitation exercise: moving the arm backward behind the body at the shoulder."
* #shoulder-circumduction "Shoulder circumduction" "Rehabilitation exercise: circular movement of the arm at the shoulder."
* #otago-knee-extension "Knee extension (Otago)" "Otago Exercise Programme movement: extending the knee."
* #otago-knee-flexion "Knee flexion / hamstring curl (Otago)" "Otago Exercise Programme movement: flexing the knee (hamstring curl)."
* #otago-hip-abduction "Hip abduction / side-leg lift (Otago)" "Otago Exercise Programme movement: lifting the leg sideways away from the body."
* #otago-hip-extension "Hip extension / back-leg lift (Otago)" "Otago Exercise Programme movement: lifting the leg backward."
* #otago-heel-raise "Heel raise (Otago)" "Otago Exercise Programme movement: rising onto the toes, raising the heels."
* #otago-toe-raise "Toe raise (Otago)" "Otago Exercise Programme movement: lifting the toes/forefoot while the heel stays down."
* #freezing-of-gait-straight-walking "Freezing of gait, straight-line walking" "Episode of gait freezing occurring during straight-line walking, in Parkinson's disease."
* #freezing-of-gait-turning "Freezing of gait, turning" "Episode of gait freezing occurring while turning, in Parkinson's disease."
* #fall-forward-lying "Fall, forward lying" "Simulated fall ending in a forward-lying position."
* #fall-front-knees-lying "Fall, front-knees lying" "Simulated fall onto the knees, ending in a lying position."
* #fall-sideward-lying "Fall, sideward lying" "Simulated fall ending in a sideward-lying position."
* #fall-backward-sitting-chair "Fall, backward onto a chair" "Simulated fall backward ending in a seated position on a chair."
* #fall-syncope "Fall, syncope" "Simulated fall due to loss of consciousness (fainting)."
* #fall-backward "Fall, backward" "Simulated fall backward."
* #fall-leftward "Fall, leftward" "Simulated fall to the left side."
* #fall-rightward "Fall, rightward" "Simulated fall to the right side."
* #fall-hitting-obstacle "Fall, hitting an obstacle" "Simulated fall in which the subject hits an obstacle while falling."
* #fall-with-protection-strategy "Fall with protection strategy" "Simulated fall in which the subject uses a protective strategy, e.g. breaking the fall with the arms."

CodeSystem: ADLLabelsCS
Id: adl-labels-cs
Title: "ADL Labels Code System"
Description: "Activities of daily living (ADL) observed during everyday life at home, such as eating, preparing food, personal hygiene and housework, taken from the reviewed HAR datasets (Supplementary Table S1), including the gestures of OPPORTUNITY and the car entry and exit of MobiAct. No suitable LOINC or SNOMED CT code was found for these. They are kept apart from GeriatricAssessmentLabelsCS because they are not prescribed movements."
* ^experimental = false
* #driving-car "Driving a car" "Operating a car as the driver."
* #having-breakfast "Having breakfast" "Eating a breakfast meal."
* #having-lunch "Having lunch" "Eating a lunch meal."
* #having-dinner "Having dinner" "Eating a dinner meal."
* #picking-up-food "Picking up food" "Collecting food, for example in a cafeteria line."
* #sitting-having-coffee "Sitting, having a coffee" "Sitting while drinking coffee."
* #standing-having-coffee "Standing, having a coffee" "Standing while drinking coffee."
* #making-coffee "Making coffee" "Preparing coffee."
* #preparing-food "Preparing food" "Preparing food, for example in a kitchen."
* #setting-table "Setting the table" "Laying out tableware in preparation for a meal."
* #washing-dishes "Washing dishes" "Washing dishes by hand."
* #washing-hands "Washing hands" "Washing the hands."
* #brushing-teeth "Brushing teeth" "Brushing the teeth."
* #personal-hygiene "Personal hygiene, unspecified" "An unspecified personal-hygiene activity."
* #using-toilet "Using the toilet" "Using the toilet."
* #standing-using-toilet "Standing, using the toilet" "Standing while using the toilet."
* #queuing "Queuing" "Standing/waiting in a queue or line."
* #fanning-barbecue "Fanning a barbecue" "Fanning a barbecue fire."
* #wiping-whiteboard "Wiping a whiteboard" "Erasing/wiping a whiteboard."
* #discussing-at-whiteboard "Discussing at a whiteboard" "Standing and gesturing at a whiteboard during discussion."
* #attending-presentation "Attending a presentation" "Sitting or standing while attending a presentation or talk."
* #watching-movie "Watching a movie" "Watching a film or video."
* #watching-tv "Watching television" "Watching television."
* #using-computer "Using a computer" "Operating a desktop or laptop computer."
* #using-phone "Using a phone" "Operating a smartphone (browsing, typing, etc.), not a voice call."
* #cleaning-room "Cleaning a room" "General room-cleaning/tidying activity."
* #vacuuming "Vacuum cleaning" "Vacuuming a floor."
* #ironing "Ironing" "Ironing clothing or fabric."
* #handling-medication "Handling medication" "Preparing or taking medication."
* #styling-hair "Styling hair" "Styling or grooming hair."
* #opening-closing-door "Opening/closing a door" "Opening or closing a door."
* #opening-closing-drawer "Opening/closing a drawer" "Opening or closing a drawer."
* #opening-closing-dishwasher "Opening/closing a dishwasher" "Opening or closing a dishwasher door."
* #opening-closing-fridge "Opening/closing a refrigerator" "Opening or closing a refrigerator door."
* #sitting-desk-activities "Sitting, desk activities" "Sitting while performing desk-based tasks (e.g. computer work, paperwork)."
* #fetching-coffee "Fetching coffee" "Walking to retrieve or get a cup of coffee, as an activity of daily living."
* #moving-between-rooms "Moving between rooms" "Ambulation transitioning from one room to another, as an activity of daily living."
* #car-step-in "Getting into a car" "Stepping into a car and sitting down."
* #car-step-out "Getting out of a car" "Standing up and stepping out of a car."
* #drinking-from-cup "Drinking from a cup" "Picking up a cup and drinking from it."
* #cleaning-table "Cleaning a table" "Wiping or cleaning a table surface."
* #toggling-switch "Toggling a light switch" "Switching a light switch on or off."

CodeSystem: AnnotationProvenanceCS
Id: annotation-provenance-cs
Title: "Annotation Provenance Code System"
Description: "How an activity label was produced, from a human annotator working alone to a fully automatic classifier. Used by the ObservationAnnotationProvenance extension."
* ^experimental = false
* #human-expert "Human expert" "The label was assigned by a human annotator or clinician working directly from the raw sensor data, without algorithmic assistance."
* #human-reviewed "Human-reviewed" "The label was initially produced by an algorithm and then reviewed and confirmed or corrected by a human annotator."
* #semi-automated "Semi-automated" "The label was produced by a workflow combining automated processing and human input in a way that is not separable into a distinct review step, for example human-assisted segmentation paired with automatic classification."
* #algorithm-generated "Algorithm-generated" "The label was assigned entirely by a classification algorithm, with no human review."

CodeSystem: SensorModalityCS
Id: sensor-modality-cs
Title: "Sensor Modality Code System"
Description: "Measured quantity (modality) of an IMU sensor channel, taken from the sensor types reported in the reviewed HAR datasets (Supplementary Table S1). No ISO/IEEE 11073, LOINC or SNOMED CT code was found for the raw signal of these sensors."
* ^experimental = false
* #accelerometer "Accelerometer" "Acceleration including gravity, as measured by an accelerometer."
* #linear-acceleration "Linear acceleration" "Acceleration with the gravity component removed, computed by the device from the accelerometer signal."
* #gravity "Gravity" "Gravity component of the acceleration, computed by the device."
* #gyroscope "Gyroscope" "Angular velocity, as measured by a gyroscope."
* #magnetometer "Magnetometer" "Magnetic field strength, as measured by a magnetometer."
* #attitude "Attitude" "Orientation of the device in space (e.g. Euler angles or quaternion), computed by the device from the other sensors."

CodeSystem: SensorAxisCS
Id: sensor-axis-cs
Title: "Sensor Axis Code System"
Description: "Axis of a multi-axis IMU signal, as given by the column of the raw data file."
* ^experimental = false
* #x "X axis" "X axis of the sensor coordinate system."
* #y "Y axis" "Y axis of the sensor coordinate system."
* #z "Z axis" "Z axis of the sensor coordinate system."
* #magnitude "Magnitude" "Magnitude (Euclidean norm) over all axes."
